blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/miccy/discussions
    about: Ask questions and discuss ideas
  - name: ğŸ“§ Email
    url: mailto:collab@miccy.dev
    about: For private inquiries
